export const TICKETS_IS_LOADING = 'TICKETS_IS_LOADING';
export const TICKETS_GET_SUCCESS = 'TICKETS_GET_SUCCESS';
export const TICKETS_HAS_ERRORED = 'TICKETS_HAS_ERRORED';
export const TICKETS_ERRORS = 'TICKETS_ERRORS';
export const TICKETS_FILTERS = 'TICKETS_FILTERS';


export const CURRENCY_IS_LOADING = 'CURRENCY_IS_LOADING';
export const CURRENCY_GET_SUCCESS = 'CURRENCY_GET_SUCCESS';
export const CURRENCY_HAS_ERRORED = 'CURRENCY_HAS_ERRORED';
export const CURRENCY_ERRORS = 'CURRENCY_ERRORS';
export const CURRENCY_CHANGE = 'CURRENCY_CHANGE';
